spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jug_lottery
    driverClassName: org.postgresql.Driver
    username: login
    password: password
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false

application:
  security:
    jwt:
      secret-key: 98ce9f0eba6c95519a279b764c47a9cc0e6a0201b002e81bcfdf18529b5cc54b