spring:
  profiles:
    active: dev
  datasource:
    url: ${DATA_SOURCE_URL}
    driverClassName: org.postgresql.Driver
    username: ${DATA_SOURCE_USERNAME}
    password: ${DATA_SOURCE_PASSWORD}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog.xml

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true
          connectiontimeout: 15000
          timeout: 10000
          writetimeout: 15000
springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v2/

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: 1800000 # ~5h